In [10]:
word='oxygen'
# word='the'

In [11]:
print(word[0])
print(word[1])
print(word[4])

o
x
e


In [12]:
for char in word:
    print(char)

o
x
y
g
e
n


In [15]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [18]:
x=1
for number in range(0,3):
    x=x * 5
print(x)

125


In [19]:
mylist=[1,3,5,7]
print(mylist)

[1, 3, 5, 7]


In [20]:
mylist[-1]

7

In [21]:
names=['Maria','Alice','James']

In [22]:
names

['Maria', 'Alice', 'James']

In [23]:
names[0]

'Maria'

In [24]:
name='Jake'

In [26]:
name='Maria'

In [27]:
name

'Maria'

In [36]:
x=[1,3,5,7]

In [37]:
y=list(x)

In [30]:
y

[1, 3, 5, 7]

In [31]:
x[0]='Darwin'

In [32]:
x

['Darwin', 3, 5, 7]

In [38]:
y

[1, 3, 5, 7]

In [43]:
string_for_slicing = 'Observation date: 02-Feb-2013'
list_for_slicing = [['fluorine', 'F'],
                    ['chlorine', 'Cl'],
                    ['bromine', 'Br'],
                    ['iodine', 'I'],
                    ['astatine', 'At']]

print(string_for_slicing[-4:])
print(list_for_slicing[-4:])

2013
[['chlorine', 'Cl'], ['bromine', 'Br'], ['iodine', 'I'], ['astatine', 'At']]


In [1]:
import numpy as np

In [3]:
data=np.loadtxt(fname='data/inflammation-01.csv', delimiter=',')

In [4]:
print(data)

[[0. 0. 1. ... 3. 0. 0.]
 [0. 1. 2. ... 1. 0. 1.]
 [0. 1. 1. ... 2. 1. 1.]
 ...
 [0. 1. 1. ... 1. 1. 1.]
 [0. 0. 0. ... 0. 2. 0.]
 [0. 0. 1. ... 1. 1. 0.]]


In [5]:
data.shape

(60, 40)

In [7]:
data[0, :].shape

(40,)

In [9]:
np.max(data), np.min(data)

(20.0, 0.0)

In [10]:
np.mean(data)

6.14875

In [11]:
np.sum(np.min(data, axis=0))

88.0

In [13]:
if np.sum(np.min(data, axis=0)) == 0:
    print('minimum sum to zero')

In [14]:
'inflammation-01.csv'.startswith('inflamm')

True

In [22]:
filenames=['inflammation-01.csv','inflammation-02.csv','inflammation-03.csv',
           'inflammation-04.csv','small-01.csv','small-02.csv','src.py']
inflammation_data=[]
small_data=[]
other_data=[]
for filename in filenames:
    if filename.startswith('inflamm'):
        inflammation_data.append(filename)
    elif filename.startswith('sma'):
        small_data.append(filename)
    else:
        other_data.append(filename)
print('inflammation_data:',inflammation_data)
print('small_data:',small_data)
print('other_data:',other_data)

inflammation_data: ['inflammation-01.csv', 'inflammation-02.csv', 'inflammation-03.csv', 'inflammation-04.csv']
small_data: ['small-01.csv', 'small-02.csv']
other_data: ['src.py']


In [25]:
def fahr_to_celsius(temp):
    return ((temp-32)*(5/9))

In [26]:
temp=68
fahr_to_celsius(temp)

20.0

In [33]:
def offset_mean(data, target_mean_value):
    
    return (data - np.mean(data)) + target_mean_value

In [34]:
offset_mean(data,2.0)

array([[-4.14875, -4.14875, -3.14875, ..., -1.14875, -4.14875, -4.14875],
       [-4.14875, -3.14875, -2.14875, ..., -3.14875, -4.14875, -3.14875],
       [-4.14875, -3.14875, -3.14875, ..., -2.14875, -3.14875, -3.14875],
       ...,
       [-4.14875, -3.14875, -3.14875, ..., -3.14875, -3.14875, -3.14875],
       [-4.14875, -4.14875, -4.14875, ..., -4.14875, -2.14875, -4.14875],
       [-4.14875, -4.14875, -3.14875, ..., -3.14875, -3.14875, -4.14875]])

In [36]:
testdata=np.zeros((3,3))
testdata

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
offset_mean(testdata,3)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [41]:
def print_message(day):
        messages={'monday': 'today is monday',
                  'tuesday': 'finally tueday',
                  'wednesday': 'today is wednesday',
                  'thursday': 'tomorrow is thursday'
                    }
        print(messages[day])
        
def print_monday_message():
    print_message('monday')
    
print_monday_message()

today is monday
